### ISSUE TITLE
Example doesn't seem to work

### ISSUE THREAD

**Issue by sentry0** [msand/zoomable-svg#1]
I'm really interested in using this lib but I can''t seem to get the example working using Expo or in my own app.

The Expo viewer on the web or my phone just crashes and my app is throwing the following error: `undefined is not an object (evaluating 'Component.propTypes')`

This tracks back to line 10 which is: `const AnimatedRect = Animated.createAnimatedComponent(Rect);`

Thoughts?

**Comment by msand** [comment]
Seems I had used the example to try and fix another issue for someone, not noticing it got saved on the example url. Can you try again? Works on android for me at least.

**Comment by SaeedZhiany** [comment]
@msand 

I just check it right now, it does not work, it shows an error message that says `undefined is not an Object evaluating (_expo.Svg.G)`
