### ISSUE TITLE
onPress of Circle  in Basic ZoomableSvg Example doesn't work

### ISSUE THREAD

**Issue by 369663841** [msand/zoomable-svg#12]
Hi, thank you for your excellent work. I try the Basic ZoomableSvg Example , it seem work fine. But when I press the Circle,it don't work. While I remove ZoomableSvg , Circle is onPress work.

React Native : 0.56.0
react-native-svg : 6.5.3
zoomable-svg : 5.0.1

I am sorry that my English is not good.

**Comment by aditya1711** [comment]
@369663841 did this work for you?

**Comment by aditya1711** [comment]
removing the double tap prop makes the on press work for me
